### ISSUE TITLE
Should probably just let you know when a chapter has already been added in the current channel

### ISSUE THREAD

**Issue by ImVexed** [RaulAkerman/MangaSnatcher#2]

**Comment by RaulAkerman** [comment]
I assume you mean when a series has already been added?

**Comment by ImVexed** [comment]
Yes, say one person does `/add asdf` then another does `/add asdf` it would respond with `Series asdf has already been added!` or something to that effect. Anything to help the effect of someone being in a server, seeing the manga bot channel, and trying to figure out which of their series has already been added etc.
